//
// Generated file, do not edit! Created by opp_msgtool 6.3 from Messages.msg.
//

#ifndef __MESSAGES_M_H
#define __MESSAGES_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SubtaskMsg;
class ResultMsg;
class RoutingMsg;
class GossipMsg;
/**
 * Class generated from <tt>Messages.msg:5</tt> by opp_msgtool.
 * <pre>
 * // Message sent to assign a subtask (subarray) to a target client
 * message SubtaskMsg
 * {
 *     int subtaskID;       // Unique subtask ID (i)
 *     int targetClientID;  // Target = subtaskID % N
 *     int originClientID;  // Who initiated this task
 *     int dataArr[];       // Subarray data
 *     int dataSize;        // Number of elements in subarray
 * }
 * </pre>
 */
class SubtaskMsg : public ::omnetpp::cMessage
{
  protected:
    int subtaskID = 0;
    int targetClientID = 0;
    int originClientID = 0;
    int *dataArr = nullptr;
    size_t dataArr_arraysize = 0;
    int dataSize = 0;

  private:
    void copy(const SubtaskMsg& other);

  protected:
    bool operator==(const SubtaskMsg&) = delete;

  public:
    SubtaskMsg(const char *name=nullptr, short kind=0);
    SubtaskMsg(const SubtaskMsg& other);
    virtual ~SubtaskMsg();
    SubtaskMsg& operator=(const SubtaskMsg& other);
    virtual SubtaskMsg *dup() const override {return new SubtaskMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSubtaskID() const;
    virtual void setSubtaskID(int subtaskID);

    virtual int getTargetClientID() const;
    virtual void setTargetClientID(int targetClientID);

    virtual int getOriginClientID() const;
    virtual void setOriginClientID(int originClientID);

    virtual void setDataArrArraySize(size_t size);
    virtual size_t getDataArrArraySize() const;
    virtual int getDataArr(size_t k) const;
    virtual void setDataArr(size_t k, int dataArr);
    virtual void insertDataArr(size_t k, int dataArr);
    [[deprecated]] void insertDataArr(int dataArr) {appendDataArr(dataArr);}
    virtual void appendDataArr(int dataArr);
    virtual void eraseDataArr(size_t k);

    virtual int getDataSize() const;
    virtual void setDataSize(int dataSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SubtaskMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SubtaskMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg:14</tt> by opp_msgtool.
 * <pre>
 * // Message sent back with the result (max) of a subtask
 * message ResultMsg
 * {
 *     int subtaskID;       // Which subtask this result belongs to
 *     int result;          // Max element found in subarray
 *     int originClientID;  // Who should receive this result
 *     int targetClientID;  // Routing target
 * }
 * </pre>
 */
class ResultMsg : public ::omnetpp::cMessage
{
  protected:
    int subtaskID = 0;
    int result = 0;
    int originClientID = 0;
    int targetClientID = 0;

  private:
    void copy(const ResultMsg& other);

  protected:
    bool operator==(const ResultMsg&) = delete;

  public:
    ResultMsg(const char *name=nullptr, short kind=0);
    ResultMsg(const ResultMsg& other);
    virtual ~ResultMsg();
    ResultMsg& operator=(const ResultMsg& other);
    virtual ResultMsg *dup() const override {return new ResultMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSubtaskID() const;
    virtual void setSubtaskID(int subtaskID);

    virtual int getResult() const;
    virtual void setResult(int result);

    virtual int getOriginClientID() const;
    virtual void setOriginClientID(int originClientID);

    virtual int getTargetClientID() const;
    virtual void setTargetClientID(int targetClientID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ResultMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ResultMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg:22</tt> by opp_msgtool.
 * <pre>
 * // Wrapper used for CHORD-based hop-by-hop routing
 * message RoutingMsg
 * {
 *     int finalDestID;     // Ultimate destination client ID
 *     string payloadType;  // "subtask" or "result"
 *     // The actual payload is embedded as a subobject via encapsulation
 * }
 * </pre>
 */
class RoutingMsg : public ::omnetpp::cMessage
{
  protected:
    int finalDestID = 0;
    omnetpp::opp_string payloadType;

  private:
    void copy(const RoutingMsg& other);

  protected:
    bool operator==(const RoutingMsg&) = delete;

  public:
    RoutingMsg(const char *name=nullptr, short kind=0);
    RoutingMsg(const RoutingMsg& other);
    virtual ~RoutingMsg();
    RoutingMsg& operator=(const RoutingMsg& other);
    virtual RoutingMsg *dup() const override {return new RoutingMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getFinalDestID() const;
    virtual void setFinalDestID(int finalDestID);

    virtual const char * getPayloadType() const;
    virtual void setPayloadType(const char * payloadType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RoutingMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RoutingMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>Messages.msg:29</tt> by opp_msgtool.
 * <pre>
 * // Gossip message broadcast after task completion
 * message GossipMsg
 * {
 *     string content;      // "<timestamp>:<IP>:<ClientID>"
 *     int originID;        // Who generated this gossip
 *     int fromID;          // Immediate sender (for loop prevention)
 * }
 * </pre>
 */
class GossipMsg : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string content;
    int originID = 0;
    int fromID = 0;

  private:
    void copy(const GossipMsg& other);

  protected:
    bool operator==(const GossipMsg&) = delete;

  public:
    GossipMsg(const char *name=nullptr, short kind=0);
    GossipMsg(const GossipMsg& other);
    virtual ~GossipMsg();
    GossipMsg& operator=(const GossipMsg& other);
    virtual GossipMsg *dup() const override {return new GossipMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getContent() const;
    virtual void setContent(const char * content);

    virtual int getOriginID() const;
    virtual void setOriginID(int originID);

    virtual int getFromID() const;
    virtual void setFromID(int fromID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GossipMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GossipMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SubtaskMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<SubtaskMsg*>(ptr.get<cObject>()); }
template<> inline ResultMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<ResultMsg*>(ptr.get<cObject>()); }
template<> inline RoutingMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<RoutingMsg*>(ptr.get<cObject>()); }
template<> inline GossipMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<GossipMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGES_M_H

